language: "fr" # your two-letter language code

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
    case_sensitive: false
  - name: CountVectorsFeaturizer
    case_sensitive: false
  - name: CountVectorsFeaturizer
    case_sensitive: false
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
