stages:
  - check
  - train
  - build
  - publish

include:
  - project: continuous-integration/templates
    file: "/v1/version.yml"
  - project: continuous-integration/templates
    file: "/v1/commitlint.yml"
  - project: continuous-integration/templates
    file: "/v1/changelog.yml"
  - project: continuous-integration/templates
    file: "/v3/.docker-check.yml"
  - project: continuous-integration/templates
    file: "/v3/.docker-build-publish.yml"

check:shell:
  image: rdeavila/docker-shellcheck:0.4.4
  stage: check
  script:
    - shellcheck bin/*.sh

check:docker:core:en:
  stage: check
  extends: .check:docker
  variables:
    DOCKERFILE_LOCATION: deployment/docker/Dockerfile.core.en

check:docker:core:fr:
  stage: check
  extends: .check:docker
  variables:
    DOCKERFILE_LOCATION: deployment/docker/Dockerfile.core.fr

check:docker:actions:
  stage: check
  extends: .check:docker
  variables:
    DOCKERFILE_LOCATION: deployment/docker/Dockerfile.actions

check:python:
  image: python:3.6.8
  stage: check
  script:
    - make install-dev
    - make install-rasa-sdk
    - make lint
    - make test
  coverage: /Total coverage:\s([0-9.]+%)/
  artifacts:
    paths:
      - htmlcov/

.train:rasa:
  image:
    name: rasa/rasa:1.9.4-full
    entrypoint: [""]
  stage: train
  script:
    - sh bin/prepare-training-data.sh ${LANGUAGE}
    - rasa train --augmentation 0 --out models/${LANGUAGE}
  artifacts:
    paths:
      - models/${LANGUAGE}

train:rasa:en:
  extends: .train:rasa
  variables:
    LANGUAGE: en

train:rasa:fr:
  extends: .train:rasa
  variables:
    LANGUAGE: fr

.docker:base:
  variables:
    DOCKER_PUBLISH_TARGETS: NUECHO
    DOCKER_IMAGE_PATH_NUECHO: covid19
    DOCKER_REGISTRY_TOKEN_NUECHO: $DOCKER_REGISTRY_TOKEN

.docker:core:en:
  extends: .docker:base
  variables:
    LANGUAGE: en
    DOCKER_IMAGE_NAME: core/en
    DOCKERFILE_LOCATION: deployment/docker/Dockerfile.core.en

.docker:core:fr:
  extends: .docker:base
  variables:
    LANGUAGE: fr
    DOCKER_IMAGE_NAME: core/fr
    DOCKERFILE_LOCATION: deployment/docker/Dockerfile.core.fr

.docker:actions:
  extends: .docker:base
  variables:
    DOCKER_IMAGE_NAME: actions
    DOCKERFILE_LOCATION: deployment/docker/Dockerfile.actions

build:docker:core:en:
  stage: build
  extends:
    - .build:docker
    - .docker:core:en

build:docker:core:fr:
  stage: build
  extends:
    - .build:docker
    - .docker:core:fr

build:docker:actions:
  stage: build
  extends:
    - .build:docker
    - .docker:actions

publish:docker:core:en:
  stage: publish
  extends:
    - .publish:docker
    - .docker:core:en

publish:docker:core:fr:
  stage: publish
  extends:
    - .publish:docker
    - .docker:core:fr

publish:docker:actions:
  stage: publish
  extends:
    - .publish:docker
    - .docker:actions
