.aliases:
  core: &core
    port: 8080
    public:
      ingress:
        websocket: true
    scale:
      horizontal: 3-12
      vertical: large
      cpuThreshold: 30
    healthcheck:
      path: /
      liveness:
        initialDelaySeconds: 15
        timeoutSeconds: 30
      readiness:
        initialDelaySeconds: 15

engine: ~1
name: covidflow
components:
  core-en:
    <<: *core
  core-fr:
    <<: *core
scale:
  memThreshold: false
environment:
  COUNTRY_CODE: ca

environments:
  dev-ca2:
    environment:
      SQL_TRACKER_STORE_URL: chloe.db.dev.dialoguecorp.com
  prod-ca:
    environment:
      SQL_TRACKER_STORE_URL: chloe.db.dialoguecorp.com
