.aliases:
  core: &core
    port: 8080
    public:
      ingress:
        paths:
          - /socket.io
        websocket: true
    scale:
      horizontal: 3-12
      vertical: medium.mem2x
    healthcheck:
      path: /
      liveness:
        initialDelaySeconds: 60
        timeoutSeconds: 30
      readiness:
        initialDelaySeconds: 60
  ingressDev: &ingressDev
    public:
      ingress:
        paths:
          - /socket.io
          - /webhooks/rest/webhook

engine: 0.0.0-77fe571
name: covidflow
scope: ops
mesh: false
components:
  core-en:
    <<: *core
  core-fr:
    <<: *core
  action-server:
    port: 8080
    scale:
      horizontal: 2-4
      vertical: small.mem
    healthcheck:
      liveness:
        timeoutSeconds: 15
      readiness:
        initialDelaySeconds: 25

addons:
  migrations:
    image:
      repo: covidflow-action-server
scale:
  memThreshold: false
environment:
  COUNTRY_CODE: ca
  ALEMBIC_DATABASE_URI: postgresql+psycopg2://$(SQL_TRACKER_STORE_USER):$(SQL_TRACKER_STORE_PASSWORD)@$(SQL_TRACKER_STORE_URL):5432/$(SQL_TRACKER_STORE_DB)
  DAILY_CHECKIN_URL_PATTERN: "https://covid19.dialogue.co/?lng={language}#/chat/ci/{reminder_id}"
  REMINDER_ID_HASHIDS_MIN_LENGTH: 8
  LOG_LEVEL: DEBUG

environments:
  dev-ca2:
    environment:
      TWILIO_NUMBER: "+14382996778"
    components:
      core-en:
        <<: *ingressDev
      core-fr:
        <<: *ingressDev
  prod-ca:
    components:
      core-en:
        public:
          ingress:
            additionalHostnames:
              - covidflow-core-en.dialogue.co
      core-fr:
        public:
          ingress:
            additionalHostnames:
              - covidflow-core-fr.dialogue.co
    environment:
      TWILIO_NUMBER: "+14382996828"
