version: "3.2"

services:
  core-en:
    build:
      context: ./core
      dockerfile: Dockerfile.en
    ports:
      - 5005:8080
    volumes:
      - ./core/models/en:/app/models
      - ./core/credentials.yml:/app/credentials.yml
      - ./core/endpoints.yml:/app/endpoints.yml
    depends_on:
      - actions
      - tracker_store

  core-fr:
    build:
      context: ./core
      dockerfile: Dockerfile.fr
    ports:
      - 5006:8080
    volumes:
      - ./core/models/fr:/app/models
      - ./core/credentials.yml:/app/credentials.yml
      - ./core/endpoints.yml:/app/endpoints.yml
    depends_on:
      - actions
      - tracker_store

  actions:
    build:
      context: ./action-server
      dockerfile: Dockerfile
    ports:
      - 5055:8080
    volumes:
      - ./action-server/actions:/app/actions

  tracker_store:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
