version: "3.2"

services:
  core-en:
    build:
      context: ./core
    ports:
      - 5005:8080
    environment:
      - SQL_TRACKER_STORE_URL=tracker-store
      - SQL_TRACKER_STORE_USER=chloe
      - SQL_TRACKER_STORE_PASSWORD=password
      - SQL_TRACKER_STORE_DB=chloe
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_NUMBER
      - LOG_LEVEL=DEBUG
      - LOG_STYLE=pretty
    volumes:
      - ./core/models/en:/app/models
      - ./core/credentials.yml:/app/credentials.yml
      - ./core/endpoints.yml:/app/endpoints.yml
      - ./core/channels:/app/channels
      - ./core/policies:/app/policies
      - ./core/core:/app/core
    depends_on:
      - action-server
      - tracker-store

  core-fr:
    build:
      context: ./core
    ports:
      - 5006:8080
    environment:
      - SQL_TRACKER_STORE_URL=tracker-store
      - SQL_TRACKER_STORE_USER=chloe
      - SQL_TRACKER_STORE_PASSWORD=password
      - SQL_TRACKER_STORE_DB=chloe
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_NUMBER
      - LOG_LEVEL=DEBUG
      - LOG_STYLE=pretty
    volumes:
      - ./core/models/fr:/app/models
      - ./core/credentials.yml:/app/credentials.yml
      - ./core/endpoints.yml:/app/endpoints.yml
      - ./core/channels:/app/channels
      - ./core/policies:/app/policies
      - ./core/core:/app/core
    depends_on:
      - action-server
      - tracker-store

  action-server:
    build:
      context: ./action-server
      dockerfile: Dockerfile
    ports:
      - 5055:8080
    environment:
      - LOG_STYLE=pretty
      - DAILY_CHECKIN_URL_PATTERN=http://localhost:3000/?lng={language}#/chat/ci/{reminder_id}
      - REMINDER_ID_HASHIDS_MIN_LENGTH=8
      - REMINDER_ID_HASHIDS_SALT=abcd1234
      - SQL_TRACKER_STORE_URL=tracker-store
      - SQL_TRACKER_STORE_USER=chloe
      - SQL_TRACKER_STORE_PASSWORD=password
      - SQL_TRACKER_STORE_DB=chloe
      - REMINDER_JOB_CORE_ENDPOINT_EN=http://core-en:8080
      - REMINDER_JOB_CORE_ENDPOINT_FR=http://core-fr:8080
      - GOOGLE_GEOCODING_API_KEY
      - GOOGLE_MAPS_API_KEY
      - GOOGLE_MAPS_URL_SIGN_SECRET
    volumes:
      - ./action-server/covidflow:/app/covidflow

  tracker-store:
    image: postgres:11
    environment:
      - POSTGRES_USER=chloe
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  db-migration:
    build:
      context: ./action-server
      dockerfile: Dockerfile
    environment:
      - ALEMBIC_DATABASE_URI=postgresql+psycopg2://chloe:password@tracker-store:5432/chloe
      - REMINDER_ID_HASHIDS_MIN_LENGTH=8
      - REMINDER_ID_HASHIDS_SALT=abcd1234
    command:
      [
        "./wait-for-it.sh",
        "tracker-store:5432",
        "-s",
        "-t",
        "120",
        "--",
        "alembic",
        "upgrade",
        "head",
      ]
    volumes:
      - ./action-server/alembic.ini:/app/alembic.ini
      - ./action-server/alembic:/app/alembic
    depends_on:
      - tracker-store
