version: 2.1

orbs:
  app: dialogue/helm-app@1.1.2
  base: dialogue/base@1.8.0
  python: dialogue/python@2.7.0
  release: dialogue/release@2.1.4

workflows:
  cicd:
    jobs:
      - mypy:
          name: (AS) mypy
          working_directory: action-server
          context: org-global-v2
      - python/pylama:
          name: (AS) pylama
          working_directory: action-server
          context: org-global-v2
      - python/isort:
          name: (AS) isort
          working_directory: action-server
          context: org-global-v2
      - python/black:
          name: (AS) black
          working_directory: action-server
          context: org-global-v2
      - python/test:
          name: (AS) test
          working_directory: action-server
          codecov_flag: action_server
          context: org-global-v2
      - app/build:
          name: (AS) build
          component: action-server
          context: org-global-v2

      - mypy:
          name: (core) mypy
          working_directory: core
          context: org-global-v2
      - python/pylama:
          name: (core) pylama
          working_directory: core
          context: org-global-v2
      - python/isort:
          name: (core) isort
          working_directory: core
          context: org-global-v2
      - python/black:
          name: (core) black
          working_directory: core
          context: org-global-v2
      - validate_domain:
          name: (core) validate_domain
          working_directory: core
          context: org-global-v2

      - prepare_core_build:
          name: (core-en) Prepare build
          context: org-global-v2
          language: en
      - app/build:
          name: (core-en) build
          component: core-en
          context: org-global-v2
          before_build_steps:
            - attach_workspace:
                at: ~/project/
          requires:
            - (core-en) Prepare build

      - prepare_core_build:
          name: (core-fr) Prepare build
          context: org-global-v2
          language: fr
      - app/build:
          name: (core-fr) build
          component: core-fr
          context: org-global-v2
          before_build_steps:
            - attach_workspace:
                at: ~/project/
          requires:
            - (core-fr) Prepare build

      - release/release:
          name: release
          context: org-global-v2
          requires:
            - (AS) mypy
            - (AS) pylama
            - (AS) isort
            - (AS) black
            - (AS) test
            - (AS) build
            - (core) mypy
            - (core) pylama
            - (core) isort
            - (core) black
            - (core) validate_domain
            - (core-en) build
            - (core-fr) build

      # dev deployments
      - app/deploy:
          name: deploy-dev-ca2-ephemeral
          stage: dev
          place: ca2
          ephemeral: yes
          requires:
            - (AS) mypy
            - (AS) pylama
            - (AS) isort
            - (AS) black
            - (AS) test
            - (AS) build
            - (core) mypy
            - (core) pylama
            - (core) isort
            - (core) black
            - (core) validate_domain
            - (core-en) build
            - (core-fr) build
          context: org-global-v2
          filters:
            branches:
              ignore: master

      - test_integration:
          name: dev-integration-tests-en
          context: org-global-v2
          working_directory: core
          language: en
          core_endpoint_url: https://${CIRCLE_PROJECT_REPONAME}-pr-${CIRCLE_PR_NUMBER}-core-en.dev.dialoguecorp.com
          requires:
            - deploy-dev-ca2-ephemeral
      - test_integration:
          name: dev-integration-tests-fr
          context: org-global-v2
          working_directory: core
          language: fr
          core_endpoint_url: https://${CIRCLE_PROJECT_REPONAME}-pr-${CIRCLE_PR_NUMBER}-core-fr.dev.dialoguecorp.com
          requires:
            - deploy-dev-ca2-ephemeral

      # master deployments
      - app/deploy:
          name: deploy-dev-ca2
          stage: dev
          place: ca2
          requires:
            - (AS) mypy
            - (AS) pylama
            - (AS) isort
            - (AS) black
            - (AS) test
            - (AS) build
            - (core) mypy
            - (core) pylama
            - (core) isort
            - (core) black
            - (core) validate_domain
            - (core-en) build
            - (core-fr) build
          context: org-global-v2
          filters:
            branches:
              only: master

      - test_integration:
          name: master-integration-tests-en
          context: org-global-v2
          filters:
            branches:
              only: master
          working_directory: core
          language: en
          core_endpoint_url: https://${CIRCLE_PROJECT_REPONAME}-core-en.dialoguecorp.com
          requires:
            - deploy-dev-ca2
      - test_integration:
          name: master-integration-tests-fr
          context: org-global-v2
          filters:
            branches:
              only: master
          working_directory: core
          language: fr
          core_endpoint_url: https://${CIRCLE_PROJECT_REPONAME}-core-fr.dialoguecorp.com
          requires:
            - deploy-dev-ca2

      - app/deploy:
          name: deploy-prod-ca
          stage: prod
          place: ca
          requires:
            - master-integration-tests-en
            - master-integration-tests-fr
          context: org-global-v2
          filters:
            branches:
              only: master

aliases:
  - &param__language
    language:
      type: string
      description: Specifies which model language to build/use
  - &param__working_directory
    working_directory:
      type: string
      default: "."
      description: Directory to run post-checkout steps
  - &param__core_endpoint_url
    core_endpoint_url:
      type: string
      description: URL pointing to the endpoint of Rasa core.

jobs:
  mypy:
    description: Checks static typing with mypy
    parameters:
      <<: *param__working_directory
    working_directory: ~/project/<<parameters.working_directory>>
    executor: python/python
    steps:
      - setup-project
      - run:
          name: Run mypy
          command: poetry run mypy .
  validate_domain:
    description: Validate Rasa domain file
    parameters:
      <<: *param__working_directory
    working_directory: ~/project/<<parameters.working_directory>>
    executor: python/python
    steps:
      - setup-project
      - run:
          name: Run validate_domain
          command: poetry run python scripts/validate_domain.py
  prepare_core_build:
    description: Prepare core help-app component (rasa-core models and docker assets)
    parameters:
      <<: *param__language
    environment:
      COMPONENT_PATH: /app/core-<<parameters.language>>
    working_directory: /app/core
    docker:
      - image: rasa/rasa:1.9.4-full
        entrypoint: ["/bin/bash"]
    steps:
      - checkout:
          path: /app
      - run:
          name: Prepare NLU training files
          command: |
            mkdir ${COMPONENT_PATH}
            cp poetry.lock ${COMPONENT_PATH}
            cp pyproject.toml ${COMPONENT_PATH}
            cp Dockerfile ${COMPONENT_PATH}
            cp credentials.yml ${COMPONENT_PATH}
            cp endpoints.yml ${COMPONENT_PATH}
      - run:
          name: Train the NLU model
          command: |
            sh scripts/prepare-training-data.sh <<parameters.language>>
            rasa train --augmentation 0 --out ${COMPONENT_PATH}/models
      - persist_to_workspace:
          root: /app
          paths:
            - core-<<parameters.language>>
  test_integration:
    description: Run integration tests against deployed dev service.
    parameters:
      <<: *param__working_directory
      <<: *param__language
      <<: *param__core_endpoint_url
    working_directory: ~/project/<<parameters.working_directory>>
    executor: python/python
    steps:
      - setup-project
      - run:
          name: Run integration tests
          command: |
            echo 'export CORE_ENDPOINT_URL=<<parameters.core_endpoint_url>>' >> $BASH_ENV
            source $BASH_ENV
            poetry run python -m rasa_integration_testing ../integration-tests-<<parameters.language>>
commands:
  setup-project:
    steps:
      - base/setup
      - python/setup
      - python/install_deps
