FROM rasa/rasa:1.9.4-full
EXPOSE 8080

ENV LOGGING_LEVEL=DEBUG
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONPATH=.

ENV ACTION_SERVER_ENDPOINT=http://action_server:8080/webhook
ENV TRACKER_STORE_ENDPOINT=tracker_store

COPY config.yml credentials.yml domain.yml endpoints.yml ./
COPY data data

RUN rasa train --augmentation 0

CMD [ "run", "--port", "8080", "--enable-api", "--debug"]
