inputs:
  poetry-version:
    description: poetry version
    required: true
runs:
  using: "composite"
  steps:
    - name: Installing poetry
      run: |
        export $( \
            PYTHONFAULTHANDLER=TRUE \
            PYTHONUNBUFFERED=TRUE \
            PIP_DISABLE_PIP_VERSION_CHECK=on \
            PIP_NO_CACHE_DIR=off \
        )
        pip install --upgrade pip \
        && pip install "poetry==${{ inputs.poetry-version }}"
      shell: bash
