# This workflow will install Python dependencies, run tests and lint both for the action server and core

name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Installing poetry 1.0.10
        uses: Gr1N/setup-poetry@v3
        with:
          poetry-version: 1.0.10
      - name: Installing dependencies
        run: make install
      - name: Linting
        run: make lint
      - name: Unit testing
        run: make test

  action-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./action-server
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Installing poetry 1.0.10
        uses: Gr1N/setup-poetry@v3
        with:
          poetry-version: 1.0.10
      - name: Installing dependencies
        run: make install
      - name: Linting
        run: make lint
      - name: Unit testing
        run: make test
